global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment_service:8001']

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:8002']
